### ISSUE TITLE
Update tests to V8 VSMYSQL / Update to vsjdbc 12.0.0

### ISSUE THREAD

**Issue by ckunki** [exasol/mysql-virtual-schema#37]
Since 2023-06-02 for version 8.18.1 of Exasol database a Docker image is available on [Dockerhub](https://hub.docker.com/layers/exasol/docker-db/8.18.1/images/sha256-33ce379848b9c2d3c0535af46a9e23382f1d3ccf5fc8c27131ba5c3e6e19a065).

The current ticket therefore requests to update the integration tests of VSMYSQL to use version 8.23.0 as latest default version.

Please note sibling-tickets for all [JDBC-based virtual schemas](https://github.com/exasol/virtual-schemas/blob/main/doc/user-guide/dialects.md).

**Comment by ckunki** [comment]
Please see ticket linked in IntRef.

**Comment by redcatbear** [comment]
A flag for more strict checking is set in V8. This breaks compatibility.

**Comment by pj-spoelders** [comment]
After some research and a few discussion with BC and CK last Friday and we've reached the conclusion that the `virtualSchemaStrictDataTypeCheck` flag that's set as 1 (true) for Exasol databases starting from v8.0 is 'at fault' for these specific tests' failure. 

I have confirmed this assumption using the following commands (using confd) to alter this flag in the docker db container:
```
docker exec -it *<container_name>* /bin/bash
confd_client -c db_stop -A '{ "db_name": "DB1"}'
confd_client -c db_configure -A '{ "db_name": "DB1", "params_add": [ "-virtualSchemaStrictDataTypeCheck=0" ]}'
confd_client -c db_start -A '{ "db_name": "DB1"}'
```
This makes the 2 failing tests succeed. 

Apparently this flag is set to false in v7.1.x. 

The ideal fix here, imho, would be to: 
- Set this flag to false in V8 as the default
- Document this database parameter, because it is currently undocumented AFAIK.

**Comment by pj-spoelders** [comment]
After a lot of discussion and research the preferred solution would be to make the VS correctly detect the Latin1 schema used in both the pushdown and the virtual schema table creation.

**Comment by ckunki** [comment]
Investigating Issues and potential changes to VSCJDBC

**Comment by pj-spoelders** [comment]
As discussed, we'll try to fix the issue in the virtual schemas itself. Doing a deep dive RN.
